# Generated by Django 6.1 on 2026-08-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0002_experiment_assignment_outcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=50)),
                ('control_n', models.IntegerField()),
                ('treatment_n', models.IntegerField()),
                ('control_rate', models.FloatField()),
                ('treatment_rate', models.FloatField()),
                ('lift', models.FloatField()),
                ('ci_lower', models.FloatField()),
                ('ci_upper', models.FloatField()),
                ('evidence_status', models.CharField(max_length=30)),
                ('sufficient_sample', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recovery.experiment')),
            ],
            options={
                'unique_together': {('experiment', 'treatment', 'segment')},
            },
        ),
    ]
