# Generated by Django 6.1 on 2026-08-24 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0004_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerState',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('opted_out', models.BooleanField(default=False)),
                ('contact_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='experimentresult',
            name='average_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('expected_net_value', models.FloatField()),
                ('estimated_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='recovery.transaction')),
            ],
        ),
    ]
